/*
Omni Gateway Manager API

Description of the Omni Gateway Manager API (managed gateways)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managed_omni_gateway

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// DefaultApiService DefaultApi service
type DefaultApiService service

// =============================================================================
// GATEWAY ENDPOINTS
// =============================================================================

// --- POST /organizations/{organizationId}/environments/{environmentId}/gateways ---

type DefaultApiCreateGatewayRequest struct {
	ctx             context.Context
	ApiService      *DefaultApiService
	organizationId  string
	environmentId   string
	gatewayPostBody *GatewayPostBody
}

func (r DefaultApiCreateGatewayRequest) GatewayPostBody(body GatewayPostBody) DefaultApiCreateGatewayRequest {
	r.gatewayPostBody = &body
	return r
}

func (r DefaultApiCreateGatewayRequest) Execute() (*Gateway, *http.Response, error) {
	return r.ApiService.CreateGatewayExecute(r)
}

func (a *DefaultApiService) CreateGateway(ctx context.Context, organizationId string, environmentId string) DefaultApiCreateGatewayRequest {
	return DefaultApiCreateGatewayRequest{ApiService: a, ctx: ctx, organizationId: organizationId, environmentId: environmentId}
}

func (a *DefaultApiService) CreateGatewayExecute(r DefaultApiCreateGatewayRequest) (*Gateway, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *Gateway
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.CreateGateway")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{organizationId}/environments/{environmentId}/gateways"
	localVarPath = strings.Replace(localVarPath, "{"+"organizationId"+"}", url.PathEscape(parameterValueToString(r.organizationId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"environmentId"+"}", url.PathEscape(parameterValueToString(r.environmentId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	localVarHTTPHeaderAccepts := []string{"application/json"}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["X-ANYPNT-ORG-ID"] = r.organizationId
	localVarHeaderParams["X-ANYPNT-ENV-ID"] = r.environmentId

	localVarPostBody = r.gatewayPostBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{body: localVarBody, error: err.Error()}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- GET /organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId} ---

type DefaultApiGetGatewayRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	organizationId string
	environmentId  string
	gatewayId      string
}

func (r DefaultApiGetGatewayRequest) Execute() (*Gateway, *http.Response, error) {
	return r.ApiService.GetGatewayExecute(r)
}

func (a *DefaultApiService) GetGateway(ctx context.Context, organizationId string, environmentId string, gatewayId string) DefaultApiGetGatewayRequest {
	return DefaultApiGetGatewayRequest{ApiService: a, ctx: ctx, organizationId: organizationId, environmentId: environmentId, gatewayId: gatewayId}
}

func (a *DefaultApiService) GetGatewayExecute(r DefaultApiGetGatewayRequest) (*Gateway, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *Gateway
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.GetGateway")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}"
	localVarPath = strings.Replace(localVarPath, "{"+"organizationId"+"}", url.PathEscape(parameterValueToString(r.organizationId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"environmentId"+"}", url.PathEscape(parameterValueToString(r.environmentId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"gatewayId"+"}", url.PathEscape(parameterValueToString(r.gatewayId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	localVarHTTPHeaderAccepts := []string{"application/json"}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["X-ANYPNT-ORG-ID"] = r.organizationId
	localVarHeaderParams["X-ANYPNT-ENV-ID"] = r.environmentId

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{body: localVarBody, error: err.Error()}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- GET /organizations/{organizationId}/environments/{environmentId}/gateways (list) ---

type DefaultApiGetGatewaysRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	organizationId string
	environmentId  string
	name           *string
	pageSize       *int32
	pageNumber     *int32
	sortBy         *string
	sortOrder      *string
}

func (r DefaultApiGetGatewaysRequest) Name(name string) DefaultApiGetGatewaysRequest {
	r.name = &name
	return r
}

func (r DefaultApiGetGatewaysRequest) PageSize(pageSize int32) DefaultApiGetGatewaysRequest {
	r.pageSize = &pageSize
	return r
}

func (r DefaultApiGetGatewaysRequest) PageNumber(pageNumber int32) DefaultApiGetGatewaysRequest {
	r.pageNumber = &pageNumber
	return r
}

func (r DefaultApiGetGatewaysRequest) Execute() (*GatewayListResponse, *http.Response, error) {
	return r.ApiService.GetGatewaysExecute(r)
}

func (a *DefaultApiService) GetGateways(ctx context.Context, organizationId string, environmentId string) DefaultApiGetGatewaysRequest {
	return DefaultApiGetGatewaysRequest{ApiService: a, ctx: ctx, organizationId: organizationId, environmentId: environmentId}
}

func (a *DefaultApiService) GetGatewaysExecute(r DefaultApiGetGatewaysRequest) (*GatewayListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *GatewayListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.GetGateways")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{organizationId}/environments/{environmentId}/gateways"
	localVarPath = strings.Replace(localVarPath, "{"+"organizationId"+"}", url.PathEscape(parameterValueToString(r.organizationId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"environmentId"+"}", url.PathEscape(parameterValueToString(r.environmentId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.name != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name", r.name, "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pageSize", r.pageSize, "")
	}
	if r.pageNumber != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pageNumber", r.pageNumber, "")
	}
	if r.sortBy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sortBy", r.sortBy, "")
	}
	if r.sortOrder != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sortOrder", r.sortOrder, "")
	}

	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	localVarHTTPHeaderAccepts := []string{"application/json"}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["X-ANYPNT-ORG-ID"] = r.organizationId
	localVarHeaderParams["X-ANYPNT-ENV-ID"] = r.environmentId

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{body: localVarBody, error: err.Error()}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- PUT /organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId} ---

type DefaultApiUpdateGatewayRequest struct {
	ctx             context.Context
	ApiService      *DefaultApiService
	organizationId  string
	environmentId   string
	gatewayId       string
	gatewayPostBody *GatewayPostBody
}

func (r DefaultApiUpdateGatewayRequest) GatewayPostBody(body GatewayPostBody) DefaultApiUpdateGatewayRequest {
	r.gatewayPostBody = &body
	return r
}

func (r DefaultApiUpdateGatewayRequest) Execute() (*Gateway, *http.Response, error) {
	return r.ApiService.UpdateGatewayExecute(r)
}

func (a *DefaultApiService) UpdateGateway(ctx context.Context, organizationId string, environmentId string, gatewayId string) DefaultApiUpdateGatewayRequest {
	return DefaultApiUpdateGatewayRequest{ApiService: a, ctx: ctx, organizationId: organizationId, environmentId: environmentId, gatewayId: gatewayId}
}

func (a *DefaultApiService) UpdateGatewayExecute(r DefaultApiUpdateGatewayRequest) (*Gateway, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *Gateway
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.UpdateGateway")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}"
	localVarPath = strings.Replace(localVarPath, "{"+"organizationId"+"}", url.PathEscape(parameterValueToString(r.organizationId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"environmentId"+"}", url.PathEscape(parameterValueToString(r.environmentId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"gatewayId"+"}", url.PathEscape(parameterValueToString(r.gatewayId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	localVarHTTPHeaderAccepts := []string{"application/json"}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["X-ANYPNT-ORG-ID"] = r.organizationId
	localVarHeaderParams["X-ANYPNT-ENV-ID"] = r.environmentId

	localVarPostBody = r.gatewayPostBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{body: localVarBody, error: err.Error()}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- DELETE /organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId} ---

type DefaultApiDeleteGatewayRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	organizationId string
	environmentId  string
	gatewayId      string
}

func (r DefaultApiDeleteGatewayRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteGatewayExecute(r)
}

func (a *DefaultApiService) DeleteGateway(ctx context.Context, organizationId string, environmentId string, gatewayId string) DefaultApiDeleteGatewayRequest {
	return DefaultApiDeleteGatewayRequest{ApiService: a, ctx: ctx, organizationId: organizationId, environmentId: environmentId, gatewayId: gatewayId}
}

func (a *DefaultApiService) DeleteGatewayExecute(r DefaultApiDeleteGatewayRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.DeleteGateway")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}"
	localVarPath = strings.Replace(localVarPath, "{"+"organizationId"+"}", url.PathEscape(parameterValueToString(r.organizationId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"environmentId"+"}", url.PathEscape(parameterValueToString(r.environmentId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"gatewayId"+"}", url.PathEscape(parameterValueToString(r.gatewayId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	localVarHTTPHeaderAccepts := []string{}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["X-ANYPNT-ORG-ID"] = r.organizationId
	localVarHeaderParams["X-ANYPNT-ENV-ID"] = r.environmentId

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

// --- GET /organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}/status ---

type DefaultApiGetGatewayStatusRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	organizationId string
	environmentId  string
	gatewayId      string
}

func (r DefaultApiGetGatewayStatusRequest) Execute() (*GatewayStatus, *http.Response, error) {
	return r.ApiService.GetGatewayStatusExecute(r)
}

func (a *DefaultApiService) GetGatewayStatus(ctx context.Context, organizationId string, environmentId string, gatewayId string) DefaultApiGetGatewayStatusRequest {
	return DefaultApiGetGatewayStatusRequest{ApiService: a, ctx: ctx, organizationId: organizationId, environmentId: environmentId, gatewayId: gatewayId}
}

func (a *DefaultApiService) GetGatewayStatusExecute(r DefaultApiGetGatewayStatusRequest) (*GatewayStatus, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *GatewayStatus
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.GetGatewayStatus")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}/status"
	localVarPath = strings.Replace(localVarPath, "{"+"organizationId"+"}", url.PathEscape(parameterValueToString(r.organizationId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"environmentId"+"}", url.PathEscape(parameterValueToString(r.environmentId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"gatewayId"+"}", url.PathEscape(parameterValueToString(r.gatewayId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	localVarHTTPHeaderAccepts := []string{"application/json"}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["X-ANYPNT-ORG-ID"] = r.organizationId
	localVarHeaderParams["X-ANYPNT-ENV-ID"] = r.environmentId

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{body: localVarBody, error: err.Error()}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- PATCH /organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}/desiredstatus ---

type DefaultApiUpdateGatewayDesiredStatusRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	organizationId string
	environmentId  string
	gatewayId      string
	body           *GatewayDesiredStatusBody
}

func (r DefaultApiUpdateGatewayDesiredStatusRequest) GatewayDesiredStatusBody(body GatewayDesiredStatusBody) DefaultApiUpdateGatewayDesiredStatusRequest {
	r.body = &body
	return r
}

func (r DefaultApiUpdateGatewayDesiredStatusRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateGatewayDesiredStatusExecute(r)
}

func (a *DefaultApiService) UpdateGatewayDesiredStatus(ctx context.Context, organizationId string, environmentId string, gatewayId string) DefaultApiUpdateGatewayDesiredStatusRequest {
	return DefaultApiUpdateGatewayDesiredStatusRequest{ApiService: a, ctx: ctx, organizationId: organizationId, environmentId: environmentId, gatewayId: gatewayId}
}

func (a *DefaultApiService) UpdateGatewayDesiredStatusExecute(r DefaultApiUpdateGatewayDesiredStatusRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPatch
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.UpdateGatewayDesiredStatus")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}/desiredstatus"
	localVarPath = strings.Replace(localVarPath, "{"+"organizationId"+"}", url.PathEscape(parameterValueToString(r.organizationId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"environmentId"+"}", url.PathEscape(parameterValueToString(r.environmentId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"gatewayId"+"}", url.PathEscape(parameterValueToString(r.gatewayId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	localVarHTTPHeaderAccepts := []string{}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["X-ANYPNT-ORG-ID"] = r.organizationId
	localVarHeaderParams["X-ANYPNT-ENV-ID"] = r.environmentId

	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
