/*
Omni Gateway Manager API

Description of the Omni Gateway Manager API (managed gateways)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managed_omni_gateway

import (
	"encoding/json"
)

var _ MappedNullable = &GatewayStatus{}

// GatewayStatus current runtime status of a managed Omni Gateway
type GatewayStatus struct {
	Status  *string `json:"status,omitempty"`
	Ready   *bool   `json:"ready,omitempty"`
	Running *bool   `json:"running,omitempty"`
}

func NewGatewayStatus() *GatewayStatus {
	this := GatewayStatus{}
	return &this
}

func NewGatewayStatusWithDefaults() *GatewayStatus {
	this := GatewayStatus{}
	return &this
}

func (o *GatewayStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}
func (o *GatewayStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}
func (o *GatewayStatus) SetStatus(v string) { o.Status = &v }

func (o *GatewayStatus) GetReady() bool {
	if o == nil || IsNil(o.Ready) {
		var ret bool
		return ret
	}
	return *o.Ready
}
func (o *GatewayStatus) GetReadyOk() (*bool, bool) {
	if o == nil || IsNil(o.Ready) {
		return nil, false
	}
	return o.Ready, true
}
func (o *GatewayStatus) SetReady(v bool) { o.Ready = &v }

func (o *GatewayStatus) GetRunning() bool {
	if o == nil || IsNil(o.Running) {
		var ret bool
		return ret
	}
	return *o.Running
}
func (o *GatewayStatus) GetRunningOk() (*bool, bool) {
	if o == nil || IsNil(o.Running) {
		return nil, false
	}
	return o.Running, true
}
func (o *GatewayStatus) SetRunning(v bool) { o.Running = &v }

func (o GatewayStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Ready) {
		toSerialize["ready"] = o.Ready
	}
	if !IsNil(o.Running) {
		toSerialize["running"] = o.Running
	}
	return toSerialize, nil
}
