/*
Omni Gateway Manager API

Description of the Omni Gateway Manager API (managed gateways)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managed_omni_gateway

import (
	"encoding/json"
)

var _ MappedNullable = &GatewayLogging{}

// GatewayLogging logging configuration for a managed Omni Gateway
type GatewayLogging struct {
	Level       *string `json:"level,omitempty"`
	ForwardLogs *bool   `json:"forwardLogs,omitempty"`
}

func NewGatewayLogging() *GatewayLogging {
	this := GatewayLogging{}
	return &this
}

func NewGatewayLoggingWithDefaults() *GatewayLogging {
	this := GatewayLogging{}
	var level string = "info"
	this.Level = &level
	var forwardLogs bool = true
	this.ForwardLogs = &forwardLogs
	return &this
}

func (o *GatewayLogging) GetLevel() string {
	if o == nil || IsNil(o.Level) {
		var ret string
		return ret
	}
	return *o.Level
}

func (o *GatewayLogging) GetLevelOk() (*string, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

func (o *GatewayLogging) SetLevel(v string) {
	o.Level = &v
}

func (o *GatewayLogging) GetForwardLogs() bool {
	if o == nil || IsNil(o.ForwardLogs) {
		var ret bool
		return ret
	}
	return *o.ForwardLogs
}

func (o *GatewayLogging) GetForwardLogsOk() (*bool, bool) {
	if o == nil || IsNil(o.ForwardLogs) {
		return nil, false
	}
	return o.ForwardLogs, true
}

func (o *GatewayLogging) SetForwardLogs(v bool) {
	o.ForwardLogs = &v
}

func (o GatewayLogging) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayLogging) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.ForwardLogs) {
		toSerialize["forwardLogs"] = o.ForwardLogs
	}
	return toSerialize, nil
}
