/*
Omni Gateway Manager API

Description of the Omni Gateway Manager API (managed gateways)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managed_omni_gateway

import (
	"encoding/json"
)

var _ MappedNullable = &GatewayConfiguration{}

// GatewayConfiguration configuration block accepted by create/update Gateway requests
type GatewayConfiguration struct {
	Ingress    *GatewayIngress    `json:"ingress,omitempty"`
	Logging    *GatewayLogging    `json:"logging,omitempty"`
	Properties *GatewayProperties `json:"properties,omitempty"`
	Tracing    *GatewayTracing    `json:"tracing,omitempty"`
}

func NewGatewayConfiguration() *GatewayConfiguration {
	this := GatewayConfiguration{}
	return &this
}

func NewGatewayConfigurationWithDefaults() *GatewayConfiguration {
	this := GatewayConfiguration{}
	return &this
}

func (o *GatewayConfiguration) GetIngress() GatewayIngress {
	if o == nil || IsNil(o.Ingress) {
		var ret GatewayIngress
		return ret
	}
	return *o.Ingress
}

func (o *GatewayConfiguration) GetIngressOk() (*GatewayIngress, bool) {
	if o == nil || IsNil(o.Ingress) {
		return nil, false
	}
	return o.Ingress, true
}

func (o *GatewayConfiguration) SetIngress(v GatewayIngress) {
	o.Ingress = &v
}

func (o *GatewayConfiguration) GetLogging() GatewayLogging {
	if o == nil || IsNil(o.Logging) {
		var ret GatewayLogging
		return ret
	}
	return *o.Logging
}

func (o *GatewayConfiguration) GetLoggingOk() (*GatewayLogging, bool) {
	if o == nil || IsNil(o.Logging) {
		return nil, false
	}
	return o.Logging, true
}

func (o *GatewayConfiguration) SetLogging(v GatewayLogging) {
	o.Logging = &v
}

func (o *GatewayConfiguration) GetProperties() GatewayProperties {
	if o == nil || IsNil(o.Properties) {
		var ret GatewayProperties
		return ret
	}
	return *o.Properties
}

func (o *GatewayConfiguration) GetPropertiesOk() (*GatewayProperties, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

func (o *GatewayConfiguration) SetProperties(v GatewayProperties) {
	o.Properties = &v
}

func (o *GatewayConfiguration) GetTracing() GatewayTracing {
	if o == nil || IsNil(o.Tracing) {
		var ret GatewayTracing
		return ret
	}
	return *o.Tracing
}

func (o *GatewayConfiguration) GetTracingOk() (*GatewayTracing, bool) {
	if o == nil || IsNil(o.Tracing) {
		return nil, false
	}
	return o.Tracing, true
}

func (o *GatewayConfiguration) SetTracing(v GatewayTracing) {
	o.Tracing = &v
}

func (o GatewayConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ingress) {
		toSerialize["ingress"] = o.Ingress
	}
	if !IsNil(o.Logging) {
		toSerialize["logging"] = o.Logging
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.Tracing) {
		toSerialize["tracing"] = o.Tracing
	}
	return toSerialize, nil
}
