/*
Omni Gateway Manager API

Description of the Omni Gateway Manager API (managed gateways)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managed_omni_gateway

import (
	"encoding/json"
)

var _ MappedNullable = &GatewayDesiredStatusBody{}

// GatewayDesiredStatusBody request body to update a gateway's desired status
type GatewayDesiredStatusBody struct {
	DesiredStatus string `json:"desiredStatus"`
}

func NewGatewayDesiredStatusBody(desiredStatus string) *GatewayDesiredStatusBody {
	this := GatewayDesiredStatusBody{}
	this.DesiredStatus = desiredStatus
	return &this
}

func NewGatewayDesiredStatusBodyWithDefaults() *GatewayDesiredStatusBody {
	this := GatewayDesiredStatusBody{}
	return &this
}

func (o *GatewayDesiredStatusBody) GetDesiredStatus() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.DesiredStatus
}
func (o *GatewayDesiredStatusBody) SetDesiredStatus(v string) { o.DesiredStatus = v }

func (o GatewayDesiredStatusBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayDesiredStatusBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["desiredStatus"] = o.DesiredStatus
	return toSerialize, nil
}
