/*
Omni Gateway Manager API

Description of the Omni Gateway Manager API (managed gateways)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managed_omni_gateway

import (
	"encoding/json"
)

var _ MappedNullable = &GatewayIngress{}

// GatewayIngress ingress configuration for a managed Omni Gateway
type GatewayIngress struct {
	PublicUrl         *string `json:"publicUrl,omitempty"`
	InternalUrl       *string `json:"internalUrl,omitempty"`
	ForwardSslSession *bool   `json:"forwardSslSession,omitempty"`
	LastMileSecurity  *bool   `json:"lastMileSecurity,omitempty"`
}

func NewGatewayIngress() *GatewayIngress {
	this := GatewayIngress{}
	return &this
}

func NewGatewayIngressWithDefaults() *GatewayIngress {
	this := GatewayIngress{}
	var forwardSslSession bool = true
	this.ForwardSslSession = &forwardSslSession
	var lastMileSecurity bool = true
	this.LastMileSecurity = &lastMileSecurity
	return &this
}

func (o *GatewayIngress) GetPublicUrl() string {
	if o == nil || IsNil(o.PublicUrl) {
		var ret string
		return ret
	}
	return *o.PublicUrl
}

func (o *GatewayIngress) GetPublicUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PublicUrl) {
		return nil, false
	}
	return o.PublicUrl, true
}

func (o *GatewayIngress) SetPublicUrl(v string) {
	o.PublicUrl = &v
}

func (o *GatewayIngress) GetInternalUrl() string {
	if o == nil || IsNil(o.InternalUrl) {
		var ret string
		return ret
	}
	return *o.InternalUrl
}

func (o *GatewayIngress) GetInternalUrlOk() (*string, bool) {
	if o == nil || IsNil(o.InternalUrl) {
		return nil, false
	}
	return o.InternalUrl, true
}

func (o *GatewayIngress) SetInternalUrl(v string) {
	o.InternalUrl = &v
}

func (o *GatewayIngress) GetForwardSslSession() bool {
	if o == nil || IsNil(o.ForwardSslSession) {
		var ret bool
		return ret
	}
	return *o.ForwardSslSession
}

func (o *GatewayIngress) GetForwardSslSessionOk() (*bool, bool) {
	if o == nil || IsNil(o.ForwardSslSession) {
		return nil, false
	}
	return o.ForwardSslSession, true
}

func (o *GatewayIngress) SetForwardSslSession(v bool) {
	o.ForwardSslSession = &v
}

func (o *GatewayIngress) GetLastMileSecurity() bool {
	if o == nil || IsNil(o.LastMileSecurity) {
		var ret bool
		return ret
	}
	return *o.LastMileSecurity
}

func (o *GatewayIngress) GetLastMileSecurityOk() (*bool, bool) {
	if o == nil || IsNil(o.LastMileSecurity) {
		return nil, false
	}
	return o.LastMileSecurity, true
}

func (o *GatewayIngress) SetLastMileSecurity(v bool) {
	o.LastMileSecurity = &v
}

func (o GatewayIngress) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayIngress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PublicUrl) {
		toSerialize["publicUrl"] = o.PublicUrl
	}
	if !IsNil(o.InternalUrl) {
		toSerialize["internalUrl"] = o.InternalUrl
	}
	if !IsNil(o.ForwardSslSession) {
		toSerialize["forwardSslSession"] = o.ForwardSslSession
	}
	if !IsNil(o.LastMileSecurity) {
		toSerialize["lastMileSecurity"] = o.LastMileSecurity
	}
	return toSerialize, nil
}
