/*
Omni Gateway Manager API

Description of the Omni Gateway Manager API (managed gateways)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managed_omni_gateway

import (
	"encoding/json"
)

var _ MappedNullable = &GatewayListResponse{}

// GatewayListResponse paginated list of managed Omni Gateways
type GatewayListResponse struct {
	Content       []Gateway `json:"content,omitempty"`
	TotalElements *int32    `json:"totalElements,omitempty"`
	PageNumber    *int32    `json:"pageNumber,omitempty"`
	PageSize      *int32    `json:"pageSize,omitempty"`
}

func NewGatewayListResponse() *GatewayListResponse {
	this := GatewayListResponse{}
	return &this
}

func NewGatewayListResponseWithDefaults() *GatewayListResponse {
	this := GatewayListResponse{}
	return &this
}

func (o *GatewayListResponse) GetContent() []Gateway {
	if o == nil || IsNil(o.Content) {
		var ret []Gateway
		return ret
	}
	return o.Content
}
func (o *GatewayListResponse) GetContentOk() ([]Gateway, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}
func (o *GatewayListResponse) SetContent(v []Gateway) { o.Content = v }

func (o *GatewayListResponse) GetTotalElements() int32 {
	if o == nil || IsNil(o.TotalElements) {
		var ret int32
		return ret
	}
	return *o.TotalElements
}
func (o *GatewayListResponse) GetTotalElementsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalElements) {
		return nil, false
	}
	return o.TotalElements, true
}
func (o *GatewayListResponse) SetTotalElements(v int32) { o.TotalElements = &v }

func (o GatewayListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.TotalElements) {
		toSerialize["totalElements"] = o.TotalElements
	}
	if !IsNil(o.PageNumber) {
		toSerialize["pageNumber"] = o.PageNumber
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	return toSerialize, nil
}
