/*
Omni Gateway Manager API

Description of the Omni Gateway Manager API (managed gateways)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managed_omni_gateway

import (
	"encoding/json"
)

var _ MappedNullable = &GatewayTracing{}

// GatewayTracing distributed tracing configuration for a managed Omni Gateway
type GatewayTracing struct {
	Enabled *bool `json:"enabled,omitempty"`
}

func NewGatewayTracing() *GatewayTracing {
	this := GatewayTracing{}
	return &this
}

func NewGatewayTracingWithDefaults() *GatewayTracing {
	this := GatewayTracing{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

func (o *GatewayTracing) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

func (o *GatewayTracing) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

func (o *GatewayTracing) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o GatewayTracing) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayTracing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}
