/*
Omni Gateway Manager API

Description of the Omni Gateway Manager API (managed gateways)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managed_omni_gateway

import (
	"encoding/json"
)

var _ MappedNullable = &Gateway{}

// Gateway represents a managed Omni Gateway instance
type Gateway struct {
	Id             *string               `json:"id,omitempty"`
	Name           *string               `json:"name,omitempty"`
	Status         *string               `json:"status,omitempty"`
	LastUpdated    *string               `json:"lastUpdated,omitempty"`
	DateCreated    *string               `json:"dateCreated,omitempty"`
	TargetId       *string               `json:"targetId,omitempty"`
	TargetName     *string               `json:"targetName,omitempty"`
	DesiredStatus  *string               `json:"desiredStatus,omitempty"`
	ReleaseChannel *string               `json:"releaseChannel,omitempty"`
	RuntimeVersion *string               `json:"runtimeVersion,omitempty"`
	Size           *string               `json:"size,omitempty"`
	ApiLimit       *float64              `json:"apiLimit,omitempty"`
	Configuration  *GatewayConfiguration `json:"configuration,omitempty"`
}

func NewGateway() *Gateway {
	this := Gateway{}
	return &this
}

func NewGatewayWithDefaults() *Gateway {
	this := Gateway{}
	return &this
}

func (o *Gateway) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}
func (o *Gateway) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}
func (o *Gateway) SetId(v string) { o.Id = &v }

func (o *Gateway) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}
func (o *Gateway) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}
func (o *Gateway) SetName(v string) { o.Name = &v }

func (o *Gateway) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}
func (o *Gateway) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}
func (o *Gateway) SetStatus(v string) { o.Status = &v }

func (o *Gateway) GetLastUpdated() string {
	if o == nil || IsNil(o.LastUpdated) {
		var ret string
		return ret
	}
	return *o.LastUpdated
}
func (o *Gateway) GetLastUpdatedOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}
func (o *Gateway) SetLastUpdated(v string) { o.LastUpdated = &v }

func (o *Gateway) GetDateCreated() string {
	if o == nil || IsNil(o.DateCreated) {
		var ret string
		return ret
	}
	return *o.DateCreated
}
func (o *Gateway) GetDateCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.DateCreated) {
		return nil, false
	}
	return o.DateCreated, true
}
func (o *Gateway) SetDateCreated(v string) { o.DateCreated = &v }

func (o *Gateway) GetTargetId() string {
	if o == nil || IsNil(o.TargetId) {
		var ret string
		return ret
	}
	return *o.TargetId
}
func (o *Gateway) GetTargetIdOk() (*string, bool) {
	if o == nil || IsNil(o.TargetId) {
		return nil, false
	}
	return o.TargetId, true
}
func (o *Gateway) SetTargetId(v string) { o.TargetId = &v }

func (o *Gateway) GetTargetName() string {
	if o == nil || IsNil(o.TargetName) {
		var ret string
		return ret
	}
	return *o.TargetName
}
func (o *Gateway) GetTargetNameOk() (*string, bool) {
	if o == nil || IsNil(o.TargetName) {
		return nil, false
	}
	return o.TargetName, true
}
func (o *Gateway) SetTargetName(v string) { o.TargetName = &v }

func (o *Gateway) GetDesiredStatus() string {
	if o == nil || IsNil(o.DesiredStatus) {
		var ret string
		return ret
	}
	return *o.DesiredStatus
}
func (o *Gateway) GetDesiredStatusOk() (*string, bool) {
	if o == nil || IsNil(o.DesiredStatus) {
		return nil, false
	}
	return o.DesiredStatus, true
}
func (o *Gateway) SetDesiredStatus(v string) { o.DesiredStatus = &v }

func (o *Gateway) GetReleaseChannel() string {
	if o == nil || IsNil(o.ReleaseChannel) {
		var ret string
		return ret
	}
	return *o.ReleaseChannel
}
func (o *Gateway) GetReleaseChannelOk() (*string, bool) {
	if o == nil || IsNil(o.ReleaseChannel) {
		return nil, false
	}
	return o.ReleaseChannel, true
}
func (o *Gateway) SetReleaseChannel(v string) { o.ReleaseChannel = &v }

func (o *Gateway) GetRuntimeVersion() string {
	if o == nil || IsNil(o.RuntimeVersion) {
		var ret string
		return ret
	}
	return *o.RuntimeVersion
}
func (o *Gateway) GetRuntimeVersionOk() (*string, bool) {
	if o == nil || IsNil(o.RuntimeVersion) {
		return nil, false
	}
	return o.RuntimeVersion, true
}
func (o *Gateway) SetRuntimeVersion(v string) { o.RuntimeVersion = &v }

func (o *Gateway) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}
func (o *Gateway) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}
func (o *Gateway) SetSize(v string) { o.Size = &v }

func (o *Gateway) GetApiLimit() float64 {
	if o == nil || IsNil(o.ApiLimit) {
		var ret float64
		return ret
	}
	return *o.ApiLimit
}
func (o *Gateway) GetApiLimitOk() (*float64, bool) {
	if o == nil || IsNil(o.ApiLimit) {
		return nil, false
	}
	return o.ApiLimit, true
}
func (o *Gateway) SetApiLimit(v float64) { o.ApiLimit = &v }

func (o *Gateway) GetConfiguration() GatewayConfiguration {
	if o == nil || IsNil(o.Configuration) {
		var ret GatewayConfiguration
		return ret
	}
	return *o.Configuration
}
func (o *Gateway) GetConfigurationOk() (*GatewayConfiguration, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}
func (o *Gateway) SetConfiguration(v GatewayConfiguration) { o.Configuration = &v }

func (o Gateway) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Gateway) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}
	if !IsNil(o.DateCreated) {
		toSerialize["dateCreated"] = o.DateCreated
	}
	if !IsNil(o.TargetId) {
		toSerialize["targetId"] = o.TargetId
	}
	if !IsNil(o.TargetName) {
		toSerialize["targetName"] = o.TargetName
	}
	if !IsNil(o.DesiredStatus) {
		toSerialize["desiredStatus"] = o.DesiredStatus
	}
	if !IsNil(o.ReleaseChannel) {
		toSerialize["releaseChannel"] = o.ReleaseChannel
	}
	if !IsNil(o.RuntimeVersion) {
		toSerialize["runtimeVersion"] = o.RuntimeVersion
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.ApiLimit) {
		toSerialize["apiLimit"] = o.ApiLimit
	}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	return toSerialize, nil
}
