/*
Omni Gateway Manager API

Description of the Omni Gateway Manager API (managed gateways)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managed_omni_gateway

import (
	"encoding/json"
)

var _ MappedNullable = &GatewayProperties{}

// GatewayProperties runtime properties for a managed Omni Gateway
type GatewayProperties struct {
	UpstreamResponseTimeout *int32 `json:"upstreamResponseTimeout,omitempty"`
	ConnectionIdleTimeout   *int32 `json:"connectionIdleTimeout,omitempty"`
}

func NewGatewayProperties() *GatewayProperties {
	this := GatewayProperties{}
	return &this
}

func NewGatewayPropertiesWithDefaults() *GatewayProperties {
	this := GatewayProperties{}
	var upstreamResponseTimeout int32 = 15
	this.UpstreamResponseTimeout = &upstreamResponseTimeout
	var connectionIdleTimeout int32 = 60
	this.ConnectionIdleTimeout = &connectionIdleTimeout
	return &this
}

func (o *GatewayProperties) GetUpstreamResponseTimeout() int32 {
	if o == nil || IsNil(o.UpstreamResponseTimeout) {
		var ret int32
		return ret
	}
	return *o.UpstreamResponseTimeout
}

func (o *GatewayProperties) GetUpstreamResponseTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.UpstreamResponseTimeout) {
		return nil, false
	}
	return o.UpstreamResponseTimeout, true
}

func (o *GatewayProperties) SetUpstreamResponseTimeout(v int32) {
	o.UpstreamResponseTimeout = &v
}

func (o *GatewayProperties) GetConnectionIdleTimeout() int32 {
	if o == nil || IsNil(o.ConnectionIdleTimeout) {
		var ret int32
		return ret
	}
	return *o.ConnectionIdleTimeout
}

func (o *GatewayProperties) GetConnectionIdleTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.ConnectionIdleTimeout) {
		return nil, false
	}
	return o.ConnectionIdleTimeout, true
}

func (o *GatewayProperties) SetConnectionIdleTimeout(v int32) {
	o.ConnectionIdleTimeout = &v
}

func (o GatewayProperties) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UpstreamResponseTimeout) {
		toSerialize["upstreamResponseTimeout"] = o.UpstreamResponseTimeout
	}
	if !IsNil(o.ConnectionIdleTimeout) {
		toSerialize["connectionIdleTimeout"] = o.ConnectionIdleTimeout
	}
	return toSerialize, nil
}
