/*
Omni Gateway Manager API

Description of the Omni Gateway Manager API (managed gateways)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managed_omni_gateway

import (
	"encoding/json"
)

var _ MappedNullable = &GatewayPostBody{}

// GatewayPostBody request body for create/update Gateway operations
type GatewayPostBody struct {
	Name           *string               `json:"name,omitempty"`
	TargetId       string                `json:"targetId"`
	ReleaseChannel string                `json:"releaseChannel"`
	RuntimeVersion string                `json:"runtimeVersion"`
	Size           string                `json:"size"`
	Configuration  *GatewayConfiguration `json:"configuration,omitempty"`
}

func NewGatewayPostBody(targetId string, releaseChannel string, runtimeVersion string, size string) *GatewayPostBody {
	this := GatewayPostBody{}
	this.TargetId = targetId
	this.ReleaseChannel = releaseChannel
	this.RuntimeVersion = runtimeVersion
	this.Size = size
	return &this
}

func NewGatewayPostBodyWithDefaults() *GatewayPostBody {
	this := GatewayPostBody{}
	this.ReleaseChannel = "lts"
	this.Size = "small"
	return &this
}

func (o *GatewayPostBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}
func (o *GatewayPostBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}
func (o *GatewayPostBody) SetName(v string) { o.Name = &v }

func (o *GatewayPostBody) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.TargetId
}
func (o *GatewayPostBody) SetTargetId(v string) { o.TargetId = v }

func (o *GatewayPostBody) GetReleaseChannel() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.ReleaseChannel
}
func (o *GatewayPostBody) SetReleaseChannel(v string) { o.ReleaseChannel = v }

func (o *GatewayPostBody) GetRuntimeVersion() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.RuntimeVersion
}
func (o *GatewayPostBody) SetRuntimeVersion(v string) { o.RuntimeVersion = v }

func (o *GatewayPostBody) GetSize() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.Size
}
func (o *GatewayPostBody) SetSize(v string) { o.Size = v }

func (o *GatewayPostBody) GetConfiguration() GatewayConfiguration {
	if o == nil || IsNil(o.Configuration) {
		var ret GatewayConfiguration
		return ret
	}
	return *o.Configuration
}
func (o *GatewayPostBody) GetConfigurationOk() (*GatewayConfiguration, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}
func (o *GatewayPostBody) SetConfiguration(v GatewayConfiguration) { o.Configuration = &v }

func (o GatewayPostBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayPostBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["targetId"] = o.TargetId
	toSerialize["releaseChannel"] = o.ReleaseChannel
	toSerialize["runtimeVersion"] = o.RuntimeVersion
	toSerialize["size"] = o.Size
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	return toSerialize, nil
}
