/*
Private Space API

Description of the Private Space API

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package private_space

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// DefaultApiService DefaultApi service
type DefaultApiService service

type DefaultApiCreatePrivateSpaceRequest struct {
	ctx                  context.Context
	ApiService           *DefaultApiService
	orgId                string
	privateSpacePostBody *PrivateSpacePostBody
}

func (r DefaultApiCreatePrivateSpaceRequest) PrivateSpacePostBody(privateSpacePostBody PrivateSpacePostBody) DefaultApiCreatePrivateSpaceRequest {
	r.privateSpacePostBody = &privateSpacePostBody
	return r
}

func (r DefaultApiCreatePrivateSpaceRequest) Execute() (*PrivateSpace, *http.Response, error) {
	return r.ApiService.CreatePrivateSpaceExecute(r)
}

/*
CreatePrivateSpace Method for CreatePrivateSpace

creates a private space for the given organization

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param orgId The ID of the organization in GUID format
	@return DefaultApiCreatePrivateSpaceRequest
*/
func (a *DefaultApiService) CreatePrivateSpace(ctx context.Context, orgId string) DefaultApiCreatePrivateSpaceRequest {
	return DefaultApiCreatePrivateSpaceRequest{
		ApiService: a,
		ctx:        ctx,
		orgId:      orgId,
	}
}

// Execute executes the request
//
//	@return PrivateSpace
func (a *DefaultApiService) CreatePrivateSpaceExecute(r DefaultApiCreatePrivateSpaceRequest) (*PrivateSpace, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpace
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.CreatePrivateSpace")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "orgId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.privateSpacePostBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DefaultApiDeletePrivateSpaceRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
}

func (r DefaultApiDeletePrivateSpaceRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeletePrivateSpaceExecute(r)
}

/*
DeletePrivateSpace Method for DeletePrivateSpace

deletes a private space for the given organization

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param orgId The ID of the organization in GUID format
	@param privateSpaceId The ID of the private space in GUID format
	@return DefaultApiDeletePrivateSpaceRequest
*/
func (a *DefaultApiService) DeletePrivateSpace(ctx context.Context, orgId string, privateSpaceId string) DefaultApiDeletePrivateSpaceRequest {
	return DefaultApiDeletePrivateSpaceRequest{
		ApiService:     a,
		ctx:            ctx,
		orgId:          orgId,
		privateSpaceId: privateSpaceId,
	}
}

// Execute executes the request
func (a *DefaultApiService) DeletePrivateSpaceExecute(r DefaultApiDeletePrivateSpaceRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.DeletePrivateSpace")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "orgId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "privateSpaceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type DefaultApiGetPrivateSpaceRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
}

func (r DefaultApiGetPrivateSpaceRequest) Execute() (*PrivateSpace, *http.Response, error) {
	return r.ApiService.GetPrivateSpaceExecute(r)
}

/*
GetPrivateSpace Method for GetPrivateSpace

retrieves a private space for the given organization

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param orgId The ID of the organization in GUID format
	@param privateSpaceId The ID of the private space in GUID format
	@return DefaultApiGetPrivateSpaceRequest
*/
func (a *DefaultApiService) GetPrivateSpace(ctx context.Context, orgId string, privateSpaceId string) DefaultApiGetPrivateSpaceRequest {
	return DefaultApiGetPrivateSpaceRequest{
		ApiService:     a,
		ctx:            ctx,
		orgId:          orgId,
		privateSpaceId: privateSpaceId,
	}
}

// Execute executes the request
//
//	@return PrivateSpace
func (a *DefaultApiService) GetPrivateSpaceExecute(r DefaultApiGetPrivateSpaceRequest) (*PrivateSpace, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpace
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.GetPrivateSpace")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "orgId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "privateSpaceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DefaultApiGetPrivateSpaceIamRolesRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
}

func (r DefaultApiGetPrivateSpaceIamRolesRequest) Execute() (*PrivateSpaceIamRoles, *http.Response, error) {
	return r.ApiService.GetPrivateSpaceIamRolesExecute(r)
}

/*
GetPrivateSpaceIamRoles Method for GetPrivateSpaceIamRoles

gets the IAM roles for the given private space

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param orgId The ID of the organization in GUID format
	@param privateSpaceId The ID of the private space in GUID format
	@return DefaultApiGetPrivateSpaceIamRolesRequest
*/
func (a *DefaultApiService) GetPrivateSpaceIamRoles(ctx context.Context, orgId string, privateSpaceId string) DefaultApiGetPrivateSpaceIamRolesRequest {
	return DefaultApiGetPrivateSpaceIamRolesRequest{
		ApiService:     a,
		ctx:            ctx,
		orgId:          orgId,
		privateSpaceId: privateSpaceId,
	}
}

// Execute executes the request
//
//	@return PrivateSpaceIamRoles
func (a *DefaultApiService) GetPrivateSpaceIamRolesExecute(r DefaultApiGetPrivateSpaceIamRolesRequest) (*PrivateSpaceIamRoles, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpaceIamRoles
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.GetPrivateSpaceIamRoles")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/iamroles"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "orgId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "privateSpaceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DefaultApiGetPrivateSpacesRequest struct {
	ctx        context.Context
	ApiService *DefaultApiService
	orgId      string
	offset     *int32
	limit      *int32
	sort       *string
	ascending  *string
}

// The offset specifies the offset of the first row to return
func (r DefaultApiGetPrivateSpacesRequest) Offset(offset int32) DefaultApiGetPrivateSpacesRequest {
	r.offset = &offset
	return r
}

// Amount of objects retrieved in the response
func (r DefaultApiGetPrivateSpacesRequest) Limit(limit int32) DefaultApiGetPrivateSpacesRequest {
	r.limit = &limit
	return r
}

// Property to sort by
func (r DefaultApiGetPrivateSpacesRequest) Sort(sort string) DefaultApiGetPrivateSpacesRequest {
	r.sort = &sort
	return r
}

// Order for sorting
func (r DefaultApiGetPrivateSpacesRequest) Ascending(ascending string) DefaultApiGetPrivateSpacesRequest {
	r.ascending = &ascending
	return r
}

func (r DefaultApiGetPrivateSpacesRequest) Execute() (*PrivateSpaceSummary, *http.Response, error) {
	return r.ApiService.GetPrivateSpacesExecute(r)
}

/*
GetPrivateSpaces Method for GetPrivateSpaces

retrieves private spaces for the given organization

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param orgId The ID of the organization in GUID format
	@return DefaultApiGetPrivateSpacesRequest
*/
func (a *DefaultApiService) GetPrivateSpaces(ctx context.Context, orgId string) DefaultApiGetPrivateSpacesRequest {
	return DefaultApiGetPrivateSpacesRequest{
		ApiService: a,
		ctx:        ctx,
		orgId:      orgId,
	}
}

// Execute executes the request
//
//	@return PrivateSpaceSummary
func (a *DefaultApiService) GetPrivateSpacesExecute(r DefaultApiGetPrivateSpacesRequest) (*PrivateSpaceSummary, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpaceSummary
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.GetPrivateSpaces")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "orgId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "")
	}
	if r.sort != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sort", r.sort, "")
	}
	if r.ascending != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ascending", r.ascending, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DefaultApiUpdatePrivateSpaceRequest struct {
	ctx                   context.Context
	ApiService            *DefaultApiService
	orgId                 string
	privateSpaceId        string
	privateSpacePatchBody *PrivateSpacePatchBody
}

func (r DefaultApiUpdatePrivateSpaceRequest) PrivateSpacePatchBody(privateSpacePatchBody PrivateSpacePatchBody) DefaultApiUpdatePrivateSpaceRequest {
	r.privateSpacePatchBody = &privateSpacePatchBody
	return r
}

func (r DefaultApiUpdatePrivateSpaceRequest) Execute() (*PrivateSpace, *http.Response, error) {
	return r.ApiService.UpdatePrivateSpaceExecute(r)
}

/*
UpdatePrivateSpace Method for UpdatePrivateSpace

updates a private space for the given organization

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param orgId The ID of the organization in GUID format
	@param privateSpaceId The ID of the private space in GUID format
	@return DefaultApiUpdatePrivateSpaceRequest
*/
func (a *DefaultApiService) UpdatePrivateSpace(ctx context.Context, orgId string, privateSpaceId string) DefaultApiUpdatePrivateSpaceRequest {
	return DefaultApiUpdatePrivateSpaceRequest{
		ApiService:     a,
		ctx:            ctx,
		orgId:          orgId,
		privateSpaceId: privateSpaceId,
	}
}

// Execute executes the request
//
//	@return PrivateSpace
func (a *DefaultApiService) UpdatePrivateSpaceExecute(r DefaultApiUpdatePrivateSpaceRequest) (*PrivateSpace, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpace
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.UpdatePrivateSpace")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "orgId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "privateSpaceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.privateSpacePatchBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// === CONNECTIONS API METHODS ===
// --- GET /connections ---
type DefaultApiGetPrivateSpaceConnectionsRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
}

func (r DefaultApiGetPrivateSpaceConnectionsRequest) Execute() ([]PrivateSpaceConnection, *http.Response, error) {
	return r.ApiService.GetPrivateSpaceConnectionsExecute(r)
}

func (a *DefaultApiService) GetPrivateSpaceConnections(ctx context.Context, orgId string, privateSpaceId string) DefaultApiGetPrivateSpaceConnectionsRequest {
	return DefaultApiGetPrivateSpaceConnectionsRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId}
}

func (a *DefaultApiService) GetPrivateSpaceConnectionsExecute(r DefaultApiGetPrivateSpaceConnectionsRequest) ([]PrivateSpaceConnection, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []PrivateSpaceConnection
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.GetPrivateSpaceConnections")
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/connections"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- POST /connections ---
type DefaultApiCreatePrivateSpaceConnectionRequest struct {
	ctx                    context.Context
	ApiService             *DefaultApiService
	orgId                  string
	privateSpaceId         string
	privateSpaceConnection *PrivateSpaceConnection
}

func (r DefaultApiCreatePrivateSpaceConnectionRequest) PrivateSpaceConnectionPostBody(privateSpaceConnection PrivateSpaceConnection) DefaultApiCreatePrivateSpaceConnectionRequest {
	r.privateSpaceConnection = &privateSpaceConnection
	return r
}

func (r DefaultApiCreatePrivateSpaceConnectionRequest) Execute() (*PrivateSpaceConnection, *http.Response, error) {
	return r.ApiService.CreatePrivateSpaceConnectionExecute(r)
}

func (a *DefaultApiService) CreatePrivateSpaceConnection(ctx context.Context, orgId string, privateSpaceId string) DefaultApiCreatePrivateSpaceConnectionRequest {
	return DefaultApiCreatePrivateSpaceConnectionRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId}
}

func (a *DefaultApiService) CreatePrivateSpaceConnectionExecute(r DefaultApiCreatePrivateSpaceConnectionRequest) (*PrivateSpaceConnection, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpaceConnection
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.CreatePrivateSpaceConnection")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/connections"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.privateSpaceConnection
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- GET /connections/{connectionId} ---
type DefaultApiGetPrivateSpaceConnectionRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
	connectionId   string
}

func (r DefaultApiGetPrivateSpaceConnectionRequest) Execute() (*PrivateSpaceConnection, *http.Response, error) {
	return r.ApiService.GetPrivateSpaceConnectionExecute(r)
}

func (a *DefaultApiService) GetPrivateSpaceConnection(ctx context.Context, orgId string, privateSpaceId string, connectionId string) DefaultApiGetPrivateSpaceConnectionRequest {
	return DefaultApiGetPrivateSpaceConnectionRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId, connectionId: connectionId}
}

func (a *DefaultApiService) GetPrivateSpaceConnectionExecute(r DefaultApiGetPrivateSpaceConnectionRequest) (*PrivateSpaceConnection, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpaceConnection
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.GetPrivateSpaceConnection")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/connections/{connectionId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- PATCH /connections/{connectionId} ---
type DefaultApiPatchPrivateSpaceConnectionRequest struct {
	ctx                    context.Context
	ApiService             *DefaultApiService
	orgId                  string
	privateSpaceId         string
	connectionId           string
	privateSpaceConnection *PrivateSpaceConnection
}

func (r DefaultApiPatchPrivateSpaceConnectionRequest) PrivateSpaceConnection(privateSpaceConnection PrivateSpaceConnection) DefaultApiPatchPrivateSpaceConnectionRequest {
	r.privateSpaceConnection = &privateSpaceConnection
	return r
}

func (r DefaultApiPatchPrivateSpaceConnectionRequest) Execute() (*PrivateSpaceConnection, *http.Response, error) {
	return r.ApiService.UpdatePrivateSpaceConnectionExecute(r)
}

func (a *DefaultApiService) UpdatePrivateSpaceConnection(ctx context.Context, orgId string, privateSpaceId string, connectionId string) DefaultApiPatchPrivateSpaceConnectionRequest {
	return DefaultApiPatchPrivateSpaceConnectionRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId, connectionId: connectionId}
}

func (a *DefaultApiService) UpdatePrivateSpaceConnectionExecute(r DefaultApiPatchPrivateSpaceConnectionRequest) (*PrivateSpaceConnection, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpaceConnection
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.PatchPrivateSpaceConnection")
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/connections/{connectionId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.privateSpaceConnection
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- DELETE /connections/{connectionId} ---
type DefaultApiDeletePrivateSpaceConnectionRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
	connectionId   string
}

func (r DefaultApiDeletePrivateSpaceConnectionRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeletePrivateSpaceConnectionExecute(r)
}

func (a *DefaultApiService) DeletePrivateSpaceConnection(ctx context.Context, orgId string, privateSpaceId string, connectionId string) DefaultApiDeletePrivateSpaceConnectionRequest {
	return DefaultApiDeletePrivateSpaceConnectionRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId, connectionId: connectionId}
}

func (a *DefaultApiService) DeletePrivateSpaceConnectionExecute(r DefaultApiDeletePrivateSpaceConnectionRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.DeletePrivateSpaceConnection")
	if err != nil {
		return nil, err
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/connections/{connectionId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

// === VPN CONNECTIONS API METHODS ===
// --- POST /connections/vpns ---
type DefaultApiPostPrivateSpaceVpnRequest struct {
	ctx                     context.Context
	ApiService              *DefaultApiService
	orgId                   string
	privateSpaceId          string
	privateSpaceVpnPostBody *PrivateSpaceConnection
}

func (r DefaultApiPostPrivateSpaceVpnRequest) PrivateSpaceVpnPostBody(privateSpaceVpnPostBody PrivateSpaceConnection) DefaultApiPostPrivateSpaceVpnRequest {
	r.privateSpaceVpnPostBody = &privateSpaceVpnPostBody
	return r
}

func (r DefaultApiPostPrivateSpaceVpnRequest) Execute() (*PrivateSpaceConnection, *http.Response, error) {
	return r.ApiService.CreatePrivateSpaceVpnExecute(r)
}

func (a *DefaultApiService) CreatePrivateSpaceVpn(ctx context.Context, orgId string, privateSpaceId string) DefaultApiPostPrivateSpaceVpnRequest {
	return DefaultApiPostPrivateSpaceVpnRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId}
}

func (a *DefaultApiService) CreatePrivateSpaceVpnExecute(r DefaultApiPostPrivateSpaceVpnRequest) (*PrivateSpaceConnection, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpaceConnection
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.CreatePrivateSpaceVpn")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/connections/vpns"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.privateSpaceVpnPostBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- PATCH /connections/vpns/{vpnId} ---
type DefaultApiPatchPrivateSpaceVpnRequest struct {
	ctx                       context.Context
	ApiService                *DefaultApiService
	orgId                     string
	privateSpaceId            string
	vpnId                     string
	privateSpaceVpnPatchtBody *PrivateSpaceVpn
}

func (r DefaultApiPatchPrivateSpaceVpnRequest) PrivateSpaceVpnPatchBody(privateSpaceVpnPatchtBody PrivateSpaceVpn) DefaultApiPatchPrivateSpaceVpnRequest {
	r.privateSpaceVpnPatchtBody = &privateSpaceVpnPatchtBody
	return r
}

func (r DefaultApiPatchPrivateSpaceVpnRequest) Execute() (*PrivateSpaceVpn, *http.Response, error) {
	return r.ApiService.UpdatePrivateSpaceVpnExecute(r)
}

func (a *DefaultApiService) UpdatePrivateSpaceVpn(ctx context.Context, orgId string, privateSpaceId string, vpnId string) DefaultApiPatchPrivateSpaceVpnRequest {
	return DefaultApiPatchPrivateSpaceVpnRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId, vpnId: vpnId}
}

func (a *DefaultApiService) UpdatePrivateSpaceVpnExecute(r DefaultApiPatchPrivateSpaceVpnRequest) (*PrivateSpaceVpn, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpaceVpn
	)
	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.UpdatePrivateSpaceVpn")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/connections/vpns/{vpnId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"vpnId"+"}", url.PathEscape(parameterValueToString(r.vpnId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.privateSpaceVpnPatchtBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil

}

// --- DELETE /connections/vpns/{vpnId} ---
type DefaultApiDeletePrivateSpaceVpnRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
	vpnId          string
}

func (r DefaultApiDeletePrivateSpaceVpnRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeletePrivateSpaceVpnExecute(r)
}

func (a *DefaultApiService) DeletePrivateSpaceVpn(ctx context.Context, orgId string, privateSpaceId string, vpnId string) DefaultApiDeletePrivateSpaceVpnRequest {
	return DefaultApiDeletePrivateSpaceVpnRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId, vpnId: vpnId}
}

func (a *DefaultApiService) DeletePrivateSpaceVpnExecute(r DefaultApiDeletePrivateSpaceVpnRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.CreatePrivateSpace")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/connections/vpns/{vpnId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"vpnId"+"}", url.PathEscape(parameterValueToString(r.vpnId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

// =============================================================================
// TRANSIT GATEWAY ENDPOINTS
// =============================================================================

// --- GET /transitgateways ---

type DefaultApiGetPrivateSpaceTransitGatewaysRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
}

func (r DefaultApiGetPrivateSpaceTransitGatewaysRequest) Execute() ([]PrivateSpaceTransitGateway, *http.Response, error) {
	return r.ApiService.GetPrivateSpaceTransitGatewaysExecute(r)
}

func (a *DefaultApiService) GetPrivateSpaceTransitGateways(ctx context.Context, orgId string, privateSpaceId string) DefaultApiGetPrivateSpaceTransitGatewaysRequest {
	return DefaultApiGetPrivateSpaceTransitGatewaysRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId}
}

func (a *DefaultApiService) GetPrivateSpaceTransitGatewaysExecute(r DefaultApiGetPrivateSpaceTransitGatewaysRequest) ([]PrivateSpaceTransitGateway, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []PrivateSpaceTransitGateway
	)
	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.GetPrivateSpaceTransitGateways")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}
	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/transitgateways"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}
	localVarHTTPHeaderAccepts := []string{"application/json"}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}
	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{body: localVarBody, error: err.Error()}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- POST /transitgateways ---

type DefaultApiCreatePrivateSpaceTransitGatewayRequest struct {
	ctx                        context.Context
	ApiService                 *DefaultApiService
	orgId                      string
	privateSpaceId             string
	privateSpaceTransitGateway *PrivateSpaceTransitGateway
}

func (r DefaultApiCreatePrivateSpaceTransitGatewayRequest) PrivateSpaceTransitGatewayPostBody(body PrivateSpaceTransitGateway) DefaultApiCreatePrivateSpaceTransitGatewayRequest {
	r.privateSpaceTransitGateway = &body
	return r
}

func (r DefaultApiCreatePrivateSpaceTransitGatewayRequest) Execute() (*PrivateSpaceTransitGateway, *http.Response, error) {
	return r.ApiService.CreatePrivateSpaceTransitGatewayExecute(r)
}

func (a *DefaultApiService) CreatePrivateSpaceTransitGateway(ctx context.Context, orgId string, privateSpaceId string) DefaultApiCreatePrivateSpaceTransitGatewayRequest {
	return DefaultApiCreatePrivateSpaceTransitGatewayRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId}
}

func (a *DefaultApiService) CreatePrivateSpaceTransitGatewayExecute(r DefaultApiCreatePrivateSpaceTransitGatewayRequest) (*PrivateSpaceTransitGateway, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpaceTransitGateway
	)
	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.CreatePrivateSpaceTransitGateway")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}
	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/transitgateways"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}
	localVarHTTPHeaderAccepts := []string{"application/json"}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarPostBody = r.privateSpaceTransitGateway
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}
	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{body: localVarBody, error: err.Error()}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- GET /transitgateways/{tgwId} ---

type DefaultApiGetPrivateSpaceTransitGatewayRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
	tgwId          string
}

func (r DefaultApiGetPrivateSpaceTransitGatewayRequest) Execute() (*PrivateSpaceTransitGateway, *http.Response, error) {
	return r.ApiService.GetPrivateSpaceTransitGatewayExecute(r)
}

func (a *DefaultApiService) GetPrivateSpaceTransitGateway(ctx context.Context, orgId string, privateSpaceId string, tgwId string) DefaultApiGetPrivateSpaceTransitGatewayRequest {
	return DefaultApiGetPrivateSpaceTransitGatewayRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId, tgwId: tgwId}
}

func (a *DefaultApiService) GetPrivateSpaceTransitGatewayExecute(r DefaultApiGetPrivateSpaceTransitGatewayRequest) (*PrivateSpaceTransitGateway, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpaceTransitGateway
	)
	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.GetPrivateSpaceTransitGateway")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}
	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/transitgateways/{tgwId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tgwId"+"}", url.PathEscape(parameterValueToString(r.tgwId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}
	localVarHTTPHeaderAccepts := []string{"application/json"}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}
	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{body: localVarBody, error: err.Error()}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- PATCH /transitgateways/{tgwId} ---

type DefaultApiUpdatePrivateSpaceTransitGatewayRequest struct {
	ctx                        context.Context
	ApiService                 *DefaultApiService
	orgId                      string
	privateSpaceId             string
	tgwId                      string
	privateSpaceTransitGateway *PrivateSpaceTransitGateway
}

func (r DefaultApiUpdatePrivateSpaceTransitGatewayRequest) PrivateSpaceTransitGatewayPatchBody(body PrivateSpaceTransitGateway) DefaultApiUpdatePrivateSpaceTransitGatewayRequest {
	r.privateSpaceTransitGateway = &body
	return r
}

func (r DefaultApiUpdatePrivateSpaceTransitGatewayRequest) Execute() (*PrivateSpaceTransitGateway, *http.Response, error) {
	return r.ApiService.UpdatePrivateSpaceTransitGatewayExecute(r)
}

func (a *DefaultApiService) UpdatePrivateSpaceTransitGateway(ctx context.Context, orgId string, privateSpaceId string, tgwId string) DefaultApiUpdatePrivateSpaceTransitGatewayRequest {
	return DefaultApiUpdatePrivateSpaceTransitGatewayRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId, tgwId: tgwId}
}

func (a *DefaultApiService) UpdatePrivateSpaceTransitGatewayExecute(r DefaultApiUpdatePrivateSpaceTransitGatewayRequest) (*PrivateSpaceTransitGateway, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PrivateSpaceTransitGateway
	)
	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.UpdatePrivateSpaceTransitGateway")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}
	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/transitgateways/{tgwId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tgwId"+"}", url.PathEscape(parameterValueToString(r.tgwId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}
	localVarHTTPHeaderAccepts := []string{"application/json"}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarPostBody = r.privateSpaceTransitGateway
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}
	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{body: localVarBody, error: err.Error()}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

// --- DELETE /transitgateways/{tgwId} ---

type DefaultApiDeletePrivateSpaceTransitGatewayRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
	tgwId          string
}

func (r DefaultApiDeletePrivateSpaceTransitGatewayRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeletePrivateSpaceTransitGatewayExecute(r)
}

func (a *DefaultApiService) DeletePrivateSpaceTransitGateway(ctx context.Context, orgId string, privateSpaceId string, tgwId string) DefaultApiDeletePrivateSpaceTransitGatewayRequest {
	return DefaultApiDeletePrivateSpaceTransitGatewayRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId, tgwId: tgwId}
}

func (a *DefaultApiService) DeletePrivateSpaceTransitGatewayExecute(r DefaultApiDeletePrivateSpaceTransitGatewayRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)
	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.DeletePrivateSpaceTransitGateway")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}
	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/transitgateways/{tgwId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tgwId"+"}", url.PathEscape(parameterValueToString(r.tgwId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}
	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}
	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}
	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarHTTPResponse, newErr
	}
	return localVarHTTPResponse, nil
}

// ─── PrivateSpaceAssociation API Methods ───────────────────────────────────

type DefaultApiCreatePrivateSpaceAssociationsRequest struct {
	ctx                            context.Context
	ApiService                     *DefaultApiService
	orgId                          string
	privateSpaceId                 string
	privateSpaceAssociationRequest *PrivateSpaceAssociationRequest
}

func (r DefaultApiCreatePrivateSpaceAssociationsRequest) PrivateSpaceAssociationBody(body PrivateSpaceAssociationRequest) DefaultApiCreatePrivateSpaceAssociationsRequest {
	r.privateSpaceAssociationRequest = &body
	return r
}

func (r DefaultApiCreatePrivateSpaceAssociationsRequest) Execute() ([]PrivateSpaceAssociation, *http.Response, error) {
	return r.ApiService.CreatePrivateSpaceAssociationsExecute(r)
}

func (a *DefaultApiService) CreatePrivateSpaceAssociations(ctx context.Context, orgId string, privateSpaceId string) DefaultApiCreatePrivateSpaceAssociationsRequest {
	return DefaultApiCreatePrivateSpaceAssociationsRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId}
}

func (a *DefaultApiService) CreatePrivateSpaceAssociationsExecute(r DefaultApiCreatePrivateSpaceAssociationsRequest) ([]PrivateSpaceAssociation, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []PrivateSpaceAssociation
	)
	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.CreatePrivateSpaceAssociations")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}
	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/associations"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}
	localVarHeaderParams["Accept"] = "application/json"
	localVarPostBody = r.privateSpaceAssociationRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}
	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type DefaultApiGetPrivateSpaceAssociationsRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
}

func (r DefaultApiGetPrivateSpaceAssociationsRequest) Execute() ([]PrivateSpaceAssociation, *http.Response, error) {
	return r.ApiService.GetPrivateSpaceAssociationsExecute(r)
}

func (a *DefaultApiService) GetPrivateSpaceAssociations(ctx context.Context, orgId string, privateSpaceId string) DefaultApiGetPrivateSpaceAssociationsRequest {
	return DefaultApiGetPrivateSpaceAssociationsRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId}
}

func (a *DefaultApiService) GetPrivateSpaceAssociationsExecute(r DefaultApiGetPrivateSpaceAssociationsRequest) ([]PrivateSpaceAssociation, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []PrivateSpaceAssociation
	)
	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.GetPrivateSpaceAssociations")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}
	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/associations"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	localVarHeaderParams["Accept"] = "application/json"
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}
	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type DefaultApiDeletePrivateSpaceAssociationRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
	associationId  string
}

func (r DefaultApiDeletePrivateSpaceAssociationRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeletePrivateSpaceAssociationExecute(r)
}

func (a *DefaultApiService) DeletePrivateSpaceAssociation(ctx context.Context, orgId string, privateSpaceId string, associationId string) DefaultApiDeletePrivateSpaceAssociationRequest {
	return DefaultApiDeletePrivateSpaceAssociationRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId, associationId: associationId}
}

func (a *DefaultApiService) DeletePrivateSpaceAssociationExecute(r DefaultApiDeletePrivateSpaceAssociationRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)
	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.DeletePrivateSpaceAssociation")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}
	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}/associations/{associationId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"associationId"+"}", url.PathEscape(parameterValueToString(r.associationId, "")), -1)
	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}
	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}
	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}
	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarHTTPResponse, newErr
	}
	return localVarHTTPResponse, nil
}

// ─── PrivateSpaceAdvancedConfig API Methods ────────────────────────────────

type DefaultApiUpdatePrivateSpaceAdvancedConfigRequest struct {
	ctx            context.Context
	ApiService     *DefaultApiService
	orgId          string
	privateSpaceId string
	body           *PrivateSpaceAdvancedConfig
}

func (r DefaultApiUpdatePrivateSpaceAdvancedConfigRequest) PrivateSpaceAdvancedConfigBody(body PrivateSpaceAdvancedConfig) DefaultApiUpdatePrivateSpaceAdvancedConfigRequest {
	r.body = &body
	return r
}

func (r DefaultApiUpdatePrivateSpaceAdvancedConfigRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdatePrivateSpaceAdvancedConfigExecute(r)
}

func (a *DefaultApiService) UpdatePrivateSpaceAdvancedConfig(ctx context.Context, orgId string, privateSpaceId string) DefaultApiUpdatePrivateSpaceAdvancedConfigRequest {
	return DefaultApiUpdatePrivateSpaceAdvancedConfigRequest{ApiService: a, ctx: ctx, orgId: orgId, privateSpaceId: privateSpaceId}
}

func (a *DefaultApiService) UpdatePrivateSpaceAdvancedConfigExecute(r DefaultApiUpdatePrivateSpaceAdvancedConfigRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPatch
		localVarPostBody   interface{}
		formFiles          []formFile
	)
	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.UpdatePrivateSpaceAdvancedConfig")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}
	localVarPath := localBasePath + "/organizations/{orgId}/privatespaces/{privateSpaceId}"
	localVarPath = strings.Replace(localVarPath, "{"+"orgId"+"}", url.PathEscape(parameterValueToString(r.orgId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"privateSpaceId"+"}", url.PathEscape(parameterValueToString(r.privateSpaceId, "")), -1)
	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}
	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}
	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}
	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{body: localVarBody, error: localVarHTTPResponse.Status}
		return localVarHTTPResponse, newErr
	}
	return localVarHTTPResponse, nil
}
