/*
Private Space API

Description of the Private Space API

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package private_space

import (
	"encoding/json"
)

// checks if the PrivateSpaceUpgradeStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateSpaceUpgradeStatus{}

// PrivateSpaceUpgradeStatus struct for PrivateSpaceUpgradeStatus
type PrivateSpaceUpgradeStatus struct {
	// Date of scheduled upgrade.
	ScheduledUpdateTime *string `json:"scheduledUpdateTime,omitempty"`
	// The upgrade status (e.g. QUEUED).
	Status *string `json:"status,omitempty"`
}

// NewPrivateSpaceUpgradeStatus instantiates a new PrivateSpaceUpgradeStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateSpaceUpgradeStatus() *PrivateSpaceUpgradeStatus {
	this := PrivateSpaceUpgradeStatus{}
	return &this
}

// NewPrivateSpaceUpgradeStatusWithDefaults instantiates a new PrivateSpaceUpgradeStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateSpaceUpgradeStatusWithDefaults() *PrivateSpaceUpgradeStatus {
	this := PrivateSpaceUpgradeStatus{}
	return &this
}

// GetScheduledUpdateTime returns the ScheduledUpdateTime field value if set, zero value otherwise.
func (o *PrivateSpaceUpgradeStatus) GetScheduledUpdateTime() string {
	if o == nil || IsNil(o.ScheduledUpdateTime) {
		var ret string
		return ret
	}
	return *o.ScheduledUpdateTime
}

// GetScheduledUpdateTimeOk returns a tuple with the ScheduledUpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateSpaceUpgradeStatus) GetScheduledUpdateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduledUpdateTime) {
		return nil, false
	}
	return o.ScheduledUpdateTime, true
}

// HasScheduledUpdateTime returns a boolean if a field has been set.
func (o *PrivateSpaceUpgradeStatus) HasScheduledUpdateTime() bool {
	if o != nil && !IsNil(o.ScheduledUpdateTime) {
		return true
	}

	return false
}

// SetScheduledUpdateTime gets a reference to the given string and assigns it to the ScheduledUpdateTime field.
func (o *PrivateSpaceUpgradeStatus) SetScheduledUpdateTime(v string) {
	o.ScheduledUpdateTime = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PrivateSpaceUpgradeStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateSpaceUpgradeStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PrivateSpaceUpgradeStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PrivateSpaceUpgradeStatus) SetStatus(v string) {
	o.Status = &v
}

func (o PrivateSpaceUpgradeStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateSpaceUpgradeStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ScheduledUpdateTime) {
		toSerialize["scheduledUpdateTime"] = o.ScheduledUpdateTime
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullablePrivateSpaceUpgradeStatus struct {
	value *PrivateSpaceUpgradeStatus
	isSet bool
}

func (v NullablePrivateSpaceUpgradeStatus) Get() *PrivateSpaceUpgradeStatus {
	return v.value
}

func (v *NullablePrivateSpaceUpgradeStatus) Set(val *PrivateSpaceUpgradeStatus) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateSpaceUpgradeStatus) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateSpaceUpgradeStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateSpaceUpgradeStatus(val *PrivateSpaceUpgradeStatus) *NullablePrivateSpaceUpgradeStatus {
	return &NullablePrivateSpaceUpgradeStatus{value: val, isSet: true}
}

func (v NullablePrivateSpaceUpgradeStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateSpaceUpgradeStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
